name: simple-fortune-cookie
on: 
  push
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout repo
       uses: actions/checkout@v4

     - name: Test frontend
       run: go test ./frontend/
  
